# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestFulltest():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_fulltest(self):
    self.driver.get("http://localhost/Expense_final/Frontend/homepage.html")
    self.driver.set_window_size(784, 816)
    time.sleep(2) 
    self.driver.find_element(By.LINK_TEXT, "Login").click()
    self.driver.find_element(By.NAME, "username").click()
    self.driver.find_element(By.NAME, "username").send_keys("vijay")
    self.driver.find_element(By.NAME, "password").click()
    self.driver.find_element(By.NAME, "password").send_keys("1234")
    time.sleep(2) 
    self.driver.find_element(By.CSS_SELECTOR, "button").click()
    self.driver.find_element(By.ID, "Expense_adder").click()
    self.driver.find_element(By.ID, "amount").click()
    self.driver.find_element(By.ID, "amount").send_keys("4500")
    self.driver.find_element(By.ID, "date").click()
    self.driver.find_element(By.ID, "date").send_keys("2024-04-16")
    self.driver.find_element(By.ID, "description").click()
    self.driver.find_element(By.ID, "description").send_keys("Accessories")
    self.driver.find_element(By.ID, "mode").click()
    self.driver.find_element(By.ID, "mode").click()
    dropdown = self.driver.find_element(By.ID, "mode")
    time.sleep(2) 
    dropdown.find_element(By.XPATH, "//option[. = 'Cash']").click()
    self.driver.find_element(By.ID, "category").click()
    dropdown = self.driver.find_element(By.ID, "category")
    dropdown.find_element(By.XPATH, "//option[. = 'Grocery']").click()
    self.driver.find_element(By.CSS_SELECTOR, "input:nth-child(11)").click()
    time.sleep(2) 
    self.driver.find_element(By.ID, "Expense_viewer").click()
    time.sleep(2) 
    self.driver.find_element(By.LINK_TEXT, "Home").click()
    self.driver.find_element(By.LINK_TEXT, "Logout").click()
    time.sleep(2) 
    self.driver.find_element(By.LINK_TEXT, "Sign up").click()
    self.driver.find_element(By.LINK_TEXT, "Sign in").click()
    time.sleep(2) 
  
